export const USER_STORAGE_NAME = '__USER__';
export const SAVE_USER_LOCAL_STORAGE = 'SAVE_USER_LOCAL_STORAGE';
export const GET_USER_LOCAL_STORAGE = 'GET_USER_LOCAL_STORAGE';
export const USER_LOGOUT = 'USER_LOGOUT';